config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about', to: "welcome#about"

  resources :payments

  resources :invoice_addon_line_items

  resources :invoices
  get 'invoices/:id/print' => 'invoices#print', as: 'invoice_print'

  resources :package_addon_types

  resources :package_types

  resources :sponsors

  get 'sponsors/state/:state' => 'sponsors#index'

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#index'

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_one :invoice

  validates :name, presence: true, length: {within: 3..40}

  state_machine :initial => :prospect do
    event :pledge do
      transition :prospect => :invoiced
    end

    event :receive_check do
      transition :invoiced => :payment_processing
    end

    event :deposit_check do
      transition :payment_processing => :payment_received
    end

    event :swipe_credit_card do
      transition :invoiced => :payment_received
    end

    event :upload_assets do
      transition :payment_received => :assets_uploaded
    end
  end

  def balance
    invoice.balance if invoice
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    if params[:state]
      @sponsors = Sponsor.where state: params[:state]
    else
      @sponsors = Sponsor.includes(:invoice).all
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sponsor }
      else
        format.html { render action: 'new' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @sponsor }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:name, :address, :note)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.haml
= simple_form_for @sponsor do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :address
    = f.input :note

  .form-actions.form-group
    = f.button :submit

app/views/sponsors/edit.html.haml
= page_header 'Editing sponsor'

= render 'form'

%a.btn.btn-default{href: url_for(@sponsor) } Cancel

app/views/sponsors/index.html.haml
%p.pull-right
  %a.btn.btn-primary{href: new_sponsor_path}
    %span.glyphicon.glyphicon-plus
    New Sponsor

= page_header 'Listing sponsors'

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Invoice
      %th Balance
      %th Note

  %tbody
    - @sponsors.each do |sponsor|
      %tr
        %td= link_to sponsor.name, sponsor
        %td
          -if invoice = sponsor.invoice
            = link_to number_to_currency(invoice.total), invoice
          -else
            = link_to 'Create Invoice', new_invoice_url(sponsor_id: sponsor.id)
        %td= number_to_currency sponsor.balance
        %td= simple_format h(sponsor.note), {}, wrapper_tag: 'div', sanitize: false

app/views/sponsors/new.html.haml
= page_header 'New sponsor'

= render 'form'

= link_to 'Back', sponsors_path

app/views/sponsors/show.html.haml
%p.pull-right
  - unless @sponsor.invoice
    %a.btn.btn-primary{href: new_invoice_url(sponsor_id: @sponsor.id)}
      %span.glyphicon.glyphicon-file
      Create Invoice

  -if @sponsor.invoice && @sponsor.invoice.balance > 0
    %a.btn.btn-primary{href: new_payment_url(invoice_id: @sponsor.invoice.id)}
      %span.glyphicon.glyphicon-file
      Add Payment

  %a.btn.btn-default{href: edit_sponsor_path(@sponsor)} Edit

= page_header "Sponsor: #{@sponsor.name}"

%dl.dl-horizontal
  %dt Balance:
  %dd= number_to_currency @sponsor.balance
  %dt Address:
  %dd= simple_format h(@sponsor.address), {}, wrapper_tag: 'div'
  %dt Note:
  %dd= simple_format h(@sponsor.note), {}, wrapper_tag: 'div'

  -if @sponsor.invoice
    %dt Invoice:
    %dd= link_to @sponsor.invoice.name, @sponsor.invoice