config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about', to: "welcome#about"

  resources :payments

  resources :invoice_addon_line_items

  resources :invoices
  get 'invoices/:id/print' => 'invoices#print', as: 'invoice_print'

  resources :package_addon_types

  resources :package_types

  resources :sponsors

  get 'sponsors/state/:state' => 'sponsors#index'

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :payment_type
  belongs_to :created_by, class_name: User

  delegate :sponsor, to: :invoice

  validates :payment_type, :invoice, presence: true
  validates :amount, numericality: {greater_than: 0}
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_many :payments

  validates :name, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.includes(:invoice).all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new invoice: Invoice.find_by_id(params[:invoice_id])
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.created_by = browserid_current_user

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @payment }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:invoice_id, :payment_type_id, :amount, :notes)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= simple_form_for(@payment) do |f|
  = f.error_notification

  .form-inputs
    = f.association :invoice
    = f.association :payment_type
    = f.input :amount
    = f.input :notes

  .form-actions.form-group
    = f.button :submit

app/views/payments/edit.html.haml
= page_header 'Editing payment'

= render 'form'

%a.btn.btn-default{href: url_for(@payment) } Cancel

app/views/payments/index.html.haml
%p.pull-right
  %a.btn.btn-primary{href: new_payment_path}
    %span.glyphicon.glyphicon-plus
    New Payment


= page_header 'Listing payments'

%table.table.table-striped
  %thead
    %tr
      %th Invoice
      %th Payment type
      %th Amount
      %th Notes
      %th
      %th

  %tbody
    - @payments.each do |payment|
      %tr
        %td= link_to payment.invoice.name, payment.invoice
        %td= payment.payment_type.name
        %td= number_to_currency payment.amount
        %td= truncate payment.notes, length: 20
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)

app/views/payments/new.html.haml
= page_header 'New payment'

= render 'form'

= link_to 'Back', payments_path

app/views/payments/show.html.haml
%p.pull-right
  %a.btn.btn-default{href: edit_payment_path(@payment)} Edit

= page_header "Payment: #{@payment.invoice.sponsor.name} (#{@payment.invoice.name})"

%dl.dl-horizontal
  %dt Invoice:
  %dd= link_to @payment.invoice.name, @payment.invoice
  %dt Payment type:
  %dd= @payment.payment_type.name
  %dt Amount:
  %dd= number_to_currency @payment.amount
  %dt Notes:
  %dd= simple_format h(@payment.notes), {}, wrapper_tag: 'div'
  %dt Created by:
  %dd= @payment.created_by.email