config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about', to: "welcome#about"

  resources :payments

  resources :invoice_addon_line_items

  resources :invoices
  get 'invoices/:id/print' => 'invoices#print', as: 'invoice_print'

  resources :package_addon_types

  resources :package_types

  resources :sponsors

  get 'sponsors/state/:state' => 'sponsors#index'

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#index'

end

app/controllers/package_addon_types_controller.rb
class PackageAddonTypesController < ApplicationController
  before_action :set_package_addon_type, only: [:show, :edit, :update, :destroy]

  # GET /package_addon_types
  # GET /package_addon_types.json
  def index
    @package_addon_types = PackageAddonType.all
  end

  # GET /package_addon_types/1
  # GET /package_addon_types/1.json
  def show
  end

  # GET /package_addon_types/new
  def new
    @package_addon_type = PackageAddonType.new
  end

  # GET /package_addon_types/1/edit
  def edit
  end

  # POST /package_addon_types
  # POST /package_addon_types.json
  def create
    @package_addon_type = PackageAddonType.new(package_addon_type_params)

    respond_to do |format|
      if @package_addon_type.save
        format.html { redirect_to @package_addon_type, notice: 'Package addon type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @package_addon_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @package_addon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_addon_types/1
  # PATCH/PUT /package_addon_types/1.json
  def update
    respond_to do |format|
      if @package_addon_type.update(package_addon_type_params)
        format.html { redirect_to @package_addon_type, notice: 'Package addon type was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @package_addon_type }
      else
        format.html { render action: 'edit' }
        format.json { render json: @package_addon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_addon_types/1
  # DELETE /package_addon_types/1.json
  def destroy
    @package_addon_type.destroy
    respond_to do |format|
      format.html { redirect_to package_addon_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_addon_type
      @package_addon_type = PackageAddonType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_addon_type_params
      params.require(:package_addon_type).permit(:name, :price, :total_spots)
    end
end

app/helpers/package_addon_types_helper.rb
module PackageAddonTypesHelper
end

app/views/package_addon_types/_form.html.haml
= simple_form_for(@package_addon_type) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :price
    = f.input :total_spots

  .form-actions.form-group
    = f.button :submit

app/views/package_addon_types/edit.html.haml
= page_header 'Editing package_addon_type'

= render 'form'

%a.btn.btn-default{href: url_for(@package_addon_type) } Cancel

app/views/package_addon_types/index.html.haml
%p.pull-right
  %a.btn.btn-primary{href: new_package_addon_type_path}
    %span.glyphicon.glyphicon-plus
    New Package addon type


= page_header 'Listing package_addon_types'

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Price
      %th Quantity remaining
      %th Total spots

  %tbody
    - @package_addon_types.each do |package_addon_type|
      %tr
        %td= link_to package_addon_type.name, package_addon_type
        %td= number_to_currency package_addon_type.price
        %td= package_addon_type.remaining
        %td= package_addon_type.total_spots

app/views/package_addon_types/new.html.haml
= page_header 'New package_addon_type'

= render 'form'

= link_to 'Back', package_addon_types_path

app/views/package_addon_types/show.html.haml
= page_header "Package addon: #{@package_addon_type.name}"

%dl.dl-horizontal
  %dt Price:
  %dd= number_to_currency @package_addon_type.price
  %dt Spots remaining:
  %dd= @package_addon_type.remaining
  %dt Total spots:
  %dd= @package_addon_type.total_spots

%a.btn.btn-default{href: edit_package_addon_type_path(@package_addon_type)} Edit

%h2 Allocated spots

%table.table.table-striped
  %thead
    %tr
      %th Sponsor
      %th Qty
  %tbody
    - @package_addon_type.invoice_addon_line_items.each do |line_item|
      %tr
        %td= link_to line_item.invoice.sponsor.name, line_item.invoice.sponsor
        %td= line_item.quantity