config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about', to: "welcome#about"

  resources :payments

  resources :invoice_addon_line_items

  resources :invoices
  get 'invoices/:id/print' => 'invoices#print', as: 'invoice_print'

  resources :package_addon_types

  resources :package_types

  resources :sponsors

  get 'sponsors/state/:state' => 'sponsors#index'

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#index'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert bg-#{name == 'notice' ? "info" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar-header
  %button.navbar-toggle(type="button" data-toggle="collapse" data-target="#navbar-collapse-root")
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  = link_to root_path, :class => 'navbar-brand' do
    = Rails.application.local_settings[:site_brand]
#navbar-collapse-root.collapse.navbar-collapse
  %ul.nav.navbar-nav
    - if browserid_authenticated?
      %li= link_to "Sponsors", sponsors_url
      %li= link_to "Invoices", invoices_url
      %li= link_to "Payments", payments_url
      %li.dropdown
        %a.dropdown-toggle(href="#" data-toggle="dropdown")Admin <b class="caret"></b>
        %ul.dropdown-menu
          %li= link_to "Package Types", package_types_url
          %li= link_to "Package Addon Types", package_addon_types_url
  %ul.nav.navbar-nav.navbar-right
    -if browserid_email
      %li= link_to "About", about_url
      %li= logout_link
    -else
      %li= login_link

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= [yield(:title), Rails.application.local_settings[:site_brand]].compact.reject(&:blank?).join ' - '
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = setup_browserid
  %body{:class => "#{controller_name} #{action_name}"}
    %nav.navbar.navbar-default{role: 'navigation'}
      = render 'layouts/navigation'
    #section-main.container{:role => "main"}
      .row
        .col-md-12
          = render 'layouts/messages'
          = yield

app/views/layouts/print-invoice.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    = stylesheet_link_tag "invoice-print", media: "all"
    %title Invoice
  %body{:class => "#{controller_name} #{action_name}"}
    = yield